export const CitiesObject = [
    { "id": 1, "name": "Sydney" },
    { "id": 2, "name": "Melbourne" },
    { "id": 3, "name": "Brisbane" },
    { "id": 4, "name": "Perth" },
    { "id": 5, "name": "Adelaide" },
    { "id": 6, "name": "Gold Coast" },
    { "id": 7, "name": "Newcastle" },
    { "id": 8, "name": "Canberra" },
    { "id": 9, "name": "Sunshine Coast" },
    { "id": 10, "name": "Wollongong" },
    { "id": 11, "name": "Hobart" },
    { "id": 12, "name": "Geelong" },
    { "id": 13, "name": "Townsville" },
    { "id": 14, "name": "Cairns" },
    { "id": 15, "name": "Darwin" },
    { "id": 16, "name": "Toowoomba" },
    { "id": 17, "name": "Ballarat" },
    { "id": 18, "name": "Bendigo" },
    { "id": 19, "name": "Albury-Wodonga" },
    { "id": 20, "name": "Launceston" },
    { "id": 21, "name": "Mackay" },
    { "id": 22, "name": "Rockhampton" },
    { "id": 23, "name": "Bunbury" },
    { "id": 24, "name": "Bundaberg" },
    { "id": 25, "name": "Coffs Harbour" },
    { "id": 26, "name": "Maitland" },
    { "id": 27, "name": "Mandurah" },
    { "id": 28, "name": "Hervey Bay" },
    { "id": 29, "name": "Mildura" },
    { "id": 30, "name": "Tamworth" },
    { "id": 31, "name": "Wagga Wagga" },
    { "id": 32, "name": "Frankston" },
    { "id": 33, "name": "Shepparton" },
    { "id": 34, "name": "Gladstone" },
    { "id": 35, "name": "Port Macquarie" },
    { "id": 36, "name": "Orange" },
    { "id": 37, "name": "Dubbo" },
    { "id": 38, "name": "Geraldton" },
    { "id": 39, "name": "Nowra" },
    { "id": 40, "name": "Bathurst" },
    { "id": 41, "name": "Warrnambool" },
    { "id": 42, "name": "Albany" },
    { "id": 43, "name": "Kalgoorlie" },
    { "id": 44, "name": "Devonport" },
    { "id": 45, "name": "Mount Gambier" },
    { "id": 46, "name": "Lismore" },
    { "id": 47, "name": "Nelson Bay" },
    { "id": 48, "name": "Busselton" },
    { "id": 49, "name": "Whyalla" },
    { "id": 50, "name": "Alice Springs" },
    { "id": 51, "name": "Goulburn" },
    { "id": 52, "name": "Mornington" },
    { "id": 53, "name": "Sunbury" },
    { "id": 54, "name": "Port Hedland" },
    { "id": 55, "name": "Grafton" },
    { "id": 56, "name": "Traralgon" },
    { "id": 57, "name": "Nowra-Bomaderry" },
    { "id": 58, "name": "Warragul" },
    { "id": 59, "name": "Bacchus Marsh" },
    { "id": 60, "name": "Horsham" },
    { "id": 61, "name": "Kwinana" },
    { "id": 62, "name": "Armidale" },
    { "id": 63, "name": "Roebourne" },
    { "id": 64, "name": "Ulverstone" },
    { "id": 65, "name": "Forster-Tuncurry" },
    { "id": 66, "name": "Broken Hill" },
    { "id": 67, "name": "Sale" },
    { "id": 68, "name": "Singleton" },
    { "id": 69, "name": "Bowen" },
    { "id": 70, "name": "Nambour" },
    { "id": 71, "name": "Kingaroy" },
    { "id": 72, "name": "Burnie" },
    { "id": 73, "name": "Yeppoon" },
    { "id": 74, "name": "Gunnedah" },
    { "id": 75, "name": "Taree" },
    { "id": 76, "name": "Muswellbrook" },
    { "id": 77, "name": "Emerald" },
    { "id": 78, "name": "Melton" },
    { "id": 79, "name": "Tuncurry" },
    { "id": 80, "name": "Portland" },
    { "id": 81, "name": "Gympie" },
    { "id": 82, "name": "Cooma" },
    { "id": 83, "name": "Port Lincoln" },
    { "id": 84, "name": "Charters Towers" },
    { "id": 85, "name": "Deniliquin" },
    { "id": 86, "name": "Kempsey" },
    { "id": 87, "name": "Bongaree" },
    { "id": 88, "name": "Griffith" },
    { "id": 89, "name": "Katherine" },
    { "id": 90, "name": "Lithgow" },
    { "id": 91, "name": "Batemans Bay" },
    { "id": 92, "name": "Murwillumbah" },
    { "id": 93, "name": "Morwell" },
    { "id": 94, "name": "Goulburn" },
    { "id": 95, "name": "Maryborough" },
    { "id": 96, "name": "Wangaratta" },
    { "id": 97, "name": "Wodonga" },
    { "id": 98, "name": "Bomaderry" },
    { "id": 99, "name": "Yamba" },
    { "id": 100, "name": "Ocean Grove-Barwon Heads" }
]